### ISSUE TITLE
😎想加本地音樂分享平台落hkdirectory入面

### ISSUE THREAD

**Issue by Fuwing** [mewedir/mewehkdirectory#16]
https://mewe.com/join/nitory

如果有手足都鍾意Hip hop/Jazz hop/Lofi同一啲moody/獨特啲既音樂類型可以禁入去我地Group睇下同分享下～
都市人接觸開Pop song，亦推薦都可以試下一啲Chill beats去放鬆下自己😎
聽住歌去搭車、行路，平時見到既街道都變成MV畫面，增添左意境～一試難忘🤤🤤

**Comment by mewedir** [comment]
Already added at post request
