### ISSUE TITLE
Lady Roselle

### ISSUE THREAD

**Issue by stephenhky** [mewedir/mewehkdirectory#3]
Add this too: https://mewe.com/group/5fc18c1c67b8dd7459b551a1

**Comment by mewedir** [comment]
Please provide a group name (Lady Roselle)? Category?

**Comment by stephenhky** [comment]
LADY ROSELLE FAN CLUB
I would put it as "KOL".
She is a KOL living in Britain talking about immigration mostly.

**Comment by mewedir** [comment]
OK, will update on next patch
