### ISSUE TITLE
你好，我想幫啲友好球迷會group submit佢地啲link

### ISSUE THREAD

**Issue by dreistreifen** [mewedir/mewehkdirectory#33]
唔知咁樣係唔係最好，我一個post俾幾個你，如果有更方便你嘅方法可以話我聽🙏🙏 唔該晒

巴塞球衣活動基地
https://mewe.com/join/barcajerseyactivitybase

香港人阿仙奴球迷會
https://mewe.com/join/香港人阿仙奴球迷會kingoflondon-arsenal

真藍黑 國際米蘭香港球迷群組
https://mewe.com/join/interfanshk

香港AC米蘭球迷會
https://mewe.com/p/hongkongacmilanfanclub1

香港紐卡素球迷會⚫⚪
https://mewe.com/p/香港紐卡素球迷會

🙏🙏🙏

**Comment by mewedir** [comment]
Done

**Comment by dreistreifen** [comment]
香港AC米蘭球迷會
https://mewe.com/p/hongkongacmilanfanclub1

香港紐卡素球迷會⚫⚪
https://mewe.com/p/香港紐卡素球迷會

你好啊，請問page係唔係未有體育category，佢地話加左入社運。唔該晒


另外可唔可以加多個group入 體育 》 足球

Dortmund Hong Kong Fans Group🟡⚫🐝
https://mewe.com/join/dortmundhongkongfansgroup
