### ISSUE TITLE
請幫我加我個裝修專頁

### ISSUE THREAD

**Issue by kk555999** [mewedir/mewehkdirectory#37]
https://mewe.com/p/kinged
kInG裝修工程公司
唔該晒

**Comment by halo2bao** [comment]
https://mewe.com/p/halo2bao
幫我加埋個網店代購THANK YOU

**Comment by mewedir** [comment]
At least give me a name, not just link T_T

**Comment by halo2bao** [comment]
kInG裝修工程公司
https://mewe.com/p/kinged

**Comment by halo2bao** [comment]
https://mewe.com/p/halo2bao
Halo雙寶代購屋
THANK YOU

**Comment by mewedir** [comment]
Done
