### ISSUE TITLE
球迷會 group/page 錯category + 新加🙏

### ISSUE THREAD

**Issue by dreistreifen** [mewedir/mewehkdirectory#40]
你好啊，呢兩個page你加左佢地入「社運」，應該係「體育」唔該晒

香港AC米蘭球迷會
https://mewe.com/p/hongkongacmilanfanclub1

香港紐卡素球迷會⚫⚪
https://mewe.com/p/香港紐卡素球迷會

另外有兩個group想加：

Dortmund Hong Kong Fans Group🟡⚫🐝
https://mewe.com/join/dortmundhongkongfansgroup

皇馬chatbox
https://mewe.com/join/realmadridzone

麻煩你🙏🙏

**Comment by mewedir** [comment]
Thanks for your correction, other is added.
