### ISSUE TITLE
Want to add a new category for workers' info exchange

### ISSUE THREAD

**Issue by oktak** [mewedir/mewehkdirectory#47]
Hello @mewedir , I have opened a pull request #45 to add 「勞工組」[MeWe](https://mewe.com/p/workercom), [for your reference, their FB ](https://www.facebook.com/workercom/)

I would like you to help to review and merge the pull request.
Thank you!

**Comment by mewedir** [comment]
Updated, any problem? 

Since the raw data is not a md file (this md is generated by other source), so I cannot just merge the pull request, if any problem, Please let me know
